Repository greenbone/gvmd, pull requests merged in 2021-07, with the labels that each got.

#1610 [master] rework docker images and ci
  .docker/build/Dockerfile
  .docker/deploy/clang/Dockerfile
  .docker/deploy/gcc/Dockerfile
  .docker/test/clang/Dockerfile
  .docker/test/gcc/Dockerfile
  .docker/testing/Dockerfile
  .github/workflows/build-and-test.yml
  .github/workflows/docker-ci.yml
Labels: backport-to-20.08, backport-to-21.04

#1613 Fix memory errors in modify_permission
  CHANGELOG.md
  src/manage_sql.c
Labels: backport-to-20.08, backport-to-21.04

#1603 Fix sending prefs for whole, growing VT families
  CHANGELOG.md
  src/manage.c
Labels: backport-to-21.04

#1618 Use less report cache SQL when adding results
  CHANGELOG.md
  src/manage.c
  src/manage.h
  src/manage_sql.c
Labels: backport-to-21.04

#1611 Fix VTs hash check and add --dump-vt-verification
  CHANGELOG.md
  src/gvmd.c
  src/manage.h
  src/manage_pg.c
  src/manage_sql_nvts.c
Labels: backport-to-20.08, backport-to-21.04

#1629 Fix creation and collation of vts_verification_str
  CHANGELOG.md
  src/manage_pg.c
Labels: backport-to-20.08, backport-to-21.04

#1633 Added retry of sensor connection for performance reports on failure.
  CHANGELOG.md
  src/manage.c
Labels: backport-to-20.08, backport-to-master

#1636 Add trash columns for target "elevate" credential
  CHANGELOG.md
  src/manage_sql.c
Labels: backport-to-21.04

#1637 Sort the "host" column by IPv4 address if possible
  CHANGELOG.md
  src/manage_sql.c
Labels: backport-to-20.08, backport-to-21.04

#1612 Add --optimize add-/cleanup-feed-permissions
  CHANGELOG.md
  INSTALL.md
  doc/gvmd.8
  doc/gvmd.8.xml
  doc/gvmd.html
  src/gvmd.c
  src/manage_sql.c
Labels: backport-to-20.08, backport-to-21.04

#1643 Fix collation for VT verification for non-UTF8 DBs
  CHANGELOG.md
  doc/gvmd.8
  doc/gvmd.8.xml
  doc/gvmd.html
  src/gvmd.c
  src/manage.h
  src/manage_pg.c
  src/manage_sql.c
Labels: backport-to-20.08, backport-to-21.04

#1644 Fix for parse_iso_time_tz error with musl library
  CHANGELOG.md
  src/manage.c
  src/manage_sql.c
  src/utils.c
Labels: backport-to-20.08, backport-to-21.04

#1651 Handle empty --vt-verification-collation correctly
  CHANGELOG.md
  doc/gvmd.8
  doc/gvmd.8.xml
  doc/gvmd.html
  src/gvmd.c
  src/manage_sql.c
Labels: backport-to-20.08, backport-to-21.04
