Repository greenbone/gvmd, pull requests merged in 2021-03, with the labels that each got.

#1439 Add --ldap-debug option
  CHANGELOG.md
  doc/gvmd.8
  doc/gvmd.8.xml
  src/gvmd.c
Labels: backport-to-21.04, backport-to-master

#1447 Fix size calculation in `--optimize vacuum`
  CHANGELOG.md
  src/manage_sql.c
Labels: backport-to-21.04, backport-to-master

#1452 Add auto retry on scanner connection lost during a runnning task
  CHANGELOG.md
  doc/gvmd.8
  doc/gvmd.8.xml
  src/gvmd.c
  src/manage.c
  src/manage.h
Labels: backport-to-21.04, backport-to-master

#1457 Show empty scores in SecInfo where appropriate
  CHANGELOG.md
  src/gmp.c
  src/manage.h
  src/manage_sql_secinfo.c
Labels: backport-to-master

#1460 Add retry if a deadlock occurs on postgres within sql#sql
  CHANGELOG.md
  src/sql.c
  src/sql_pg.c
Labels: backport-to-master

#1462 Fix report host end time check in CVE scans
  CHANGELOG.md
  src/manage_sql.c
Labels: backport-to-21.04, backport-to-master

#1466 Don't require report format for XML report
  CHANGELOG.md
  src/gmp.c
  src/manage_sql.c
  src/manage_sql_report_formats.c
  src/manage_sql_report_formats.h
Labels: backport-to-master

#1468 Generate GMP documentation in CircleCI
  .circleci/config.yml
Labels: backport-to-20.08, backport-to-master
