Repository greenbone/gvmd, pull requests merged in 2021-05, with the labels that each got.

#1505 Use pba authentication instead of authutils
  .gitignore
  CHANGELOG.md
  src/CMakeLists.txt
  src/gvmd.c
  src/manage_authentication.c
  src/manage_authentication.h
  src/manage_sql.c
Labels: backport-to-20.08, backport-to-21.04

#1517 Fix whole-only config family selection
  CHANGELOG.md
  src/gmp_configs.c
  src/manage_configs.h
  src/manage_sql_configs.c
Labels: backport-to-master

#1518 Enhance datetime parsing when using h instead of :
  CHANGELOG.md
  src/manage_sql.c
Labels: backport-to-20.08, backport-to-21.04

#1526 Free alert get data in report_content_for_alert
  CHANGELOG.md
  src/manage_sql.c
Labels: backport-to-20.08, backport-to-21.04

#1524 Fix typos.
  src/gmp_configs.c
  src/sql.c
Labels: backport-to-master

#1530 Fix erroneous freeing of ical timezone component
  CHANGELOG.md
  src/manage_utils.c
Labels: backport-to-20.08, backport-to-21.04

#1536 Add NVT tag "deprecated"
  CHANGELOG.md
  src/manage_sql_nvts.c
Labels: backport-to-21.04
