Repository greenbone/gvmd, pull requests merged in 2021-06, with the labels that each got.

#1539 Include new ssh elevate credential login data in OSP request
  CHANGELOG.md
  src/manage.c
Labels: backport-to-21.04

#1546 Fixed the sorting / filter by username functionality for remediation tickets
  CHANGELOG.md
  src/manage_sql_tickets.c
Labels: backport-to-20.08, backport-to-master

#1552 Replace CircleCI with GitHub Actions
  .circleci/config.yml
  .github/workflows/build-and-test.yml
Labels: backport-to-20.08, backport-to-21.04

#1553 The alterable indicator is now copied when cloning a task.
  CHANGELOG.md
  src/gmp.c
  src/manage_sql.c
Labels: backport-to-20.08, backport-to-21.04

#1560 Fix security issues: replace localtime with localtime_r
  src/manage_sql.c
  src/manage_utils.c
  src/utils.c
Labels: backport-to-20.08, backport-to-21.04

#1563 Replace ctime with ctime_r
  src/manage.c
  src/manage_sql.c
Labels: backport-to-20.08, backport-to-21.04

#1568 Fix stop resume
  CHANGELOG.md
  src/manage.c
Labels: backport-to-21.04, backport-to-master

#1575 Set file permissions in greenbone-feed-sync
  CHANGELOG.md
  tools/greenbone-feed-sync.in
Labels: backport-to-20.08, backport-to-21.04

#1567 Solved a peformance problem for tasks after scanning lots of hosts.
  CHANGELOG.md
  src/manage_sql.c
Labels: backport-to-21.04

#1580 Fix workflow and release 20.8.2
  .github/workflows/build-and-test.yml
  .github/workflows/release-pontos-patch.yml
  .gitignore
  CMakeLists.txt
  INSTALL.md
  src/CMakeLists.txt
Labels: make patch release

#1582 Added a test, if the ssh_elevate_credential is different from the ssh_credential.
  CHANGELOG.md
  src/gmp.c
  src/manage_sql.c
Labels: backport-to-master

#1579 Solved a performance problem when filtering results by tags.
  CHANGELOG.md
  src/manage_pg.c
Labels: backport-to-master

#1581 Fix Workflow and release 21.4.1
  .github/workflows/build-and-test.yml
  .github/workflows/release-pontos-patch.yml
  .gitignore
  CMakeLists.txt
  INSTALL.md
  src/CMakeLists.txt
Labels: make patch release

#1591 Added the GMP documentation for the ssh_elevate_credential.
  CHANGELOG.md
  src/schema_formats/XML/GMP.xml.in
Labels: backport-to-21.04
