Repository greenbone/gvmd, pull requests merged in 2021-08, with the labels that each got.

#1655 Always quote C collation
  CHANGELOG.md
  src/manage_pg.c
Labels: backport-to-21.04, backport-to-master

#1659 [20.08] Add signing to workflow ...
  .github/workflows/release-pontos-patch.yml
Labels: make patch release

#1660 [20.08] Add signing to workflow ... (again)
  .github/workflows/release-pontos-patch.yml
Labels: make patch release

#1661 [21.04] Add signing to workflow ...
  .github/workflows/release-pontos-patch.yml
Labels: make patch release

#1665 Use a saner default for GVM_FEED_LOCK_PATH
  CHANGELOG.md
  CMakeLists.txt
Labels: backport-to-master, backport-to-21.04

#1673 Remove BID from GMP documentation
  CHANGELOG.md
  src/schema_formats/XML/GMP.xml.in
Labels: backport-to-20.08, backport-to-21.04

#1666 Adjusted the lack of the severities in the display of applications.
  CHANGELOG.md
  src/gmp.c
  src/manage_sql.c
Labels: backport-to-20.08, backport-to-master
