Repository greenbone/gvmd, pull requests merged in 2023-04, with the labels that each got.

#1941 Added action dependency review
  .github/workflows/dependency-review.yml
Labels: action

#1938 Filter duplicate results from the scanner during report generation.
  CMakeLists.txt
  src/manage.c
  src/manage.h
  src/manage_migrators.c
  src/manage_sql.c
Labels: backport-to-stable

#1946 Change: Make installing feed sync scripts optional
  CMakeLists.txt
  doc/CMakeLists.txt
Labels: backport-to-main

#1940 Skip SQL statements to speed up rebuild
  src/manage_sql_nvts.c
Labels: backport-to-stable

#1949 Added composite action SPDX to dependency graph
  .github/workflows/sbom-upload.yml
Labels: action

#1951 Fix: Find resources for feed role permissions without checking the owner
  src/manage.h
  src/manage_sql.c
Labels: backport-to-stable

#1954 Change: Show false positives in reports list by default
  src/gmp.c
  src/manage_sql.c
Labels: backport-to-stable

#1944 Rebuild NVTs in shadow tables
  src/manage.h
  src/manage_pg.c
  src/manage_sql_configs.c
  src/manage_sql_nvts.c
Labels: backport-to-stable

#1955 Combine INSERTs into vt_refs when updating/rebuilding
  src/manage_sql_nvts.c
Labels: backport-to-stable

#1960 Fix: Use severity column in CVEs alert iterators
  src/manage_sql.c
Labels: backport-to-stable

#1961 Fix: Fix result detection for imported reports
  src/gmp.c
Labels: backport-to-stable
