Repository greenbone/gvmd, pull requests merged in 2023-07, with the labels that each got.

#2032 Fix pattern match for migrating preferences
  src/manage_migrators.c
Labels: backport-to-stable, patch release

#2036 Fix: Make matching for prefs migration stricter
  src/manage_migrators.c
Labels: backport-to-stable, patch release

#2040 Fix: Fix check_preference_names iterator
  src/manage_sql_nvts.c
Labels: backport-to-stable

#2042 Fix: Handle close_connection when writefds is 0
  src/gmpd.c
Labels: patch release

#2044 Fix: Convert severity & qod to numbers in check_osp_result_exists
  src/manage_sql.c
Labels: backport-to-stable, patch release
